export interface EditarCedula{
    finalidad: number | null,
    urgencia: number | null,
    nombreFiscal: string,
    descripcion: string,
    modalidadCitacion?: string,
    direccionCitacion?: string,
    referenciaCitacion?: string,
    direccionUrlCitacion?: string,
    fechaHoraCitacion?: string,
    camaraGesellCitacion?: number | null,
    agraviadoCitacion?: string | null,
    denunciadoCitacion?: string | null,
    personaSolicitanteCitacion?: string | null,
    numeroCitacion?: string | null,
    documentoARecibir?: string,
    diasHabiles?: string,
    motivoConciliacionCitacion?: string,
    fechaCitacion?: Date,
    horaCitacion?: Date,
}