export interface SujetoQueja {
  idSujetoCaso?: string,
  nombreSujeto?: string,
  idTipoParteSujeto?: number,
  tipoParteSujeto?: string,
  idResultadoPrimera?: number,
  resultadoPrimera?: string,
  idRespuestaInstancia?: number,
  respuestaInstancia?: string,
  tieneApelacion?: string,
  usuarioApelacion?: string,
  estadoQueja?: string,
  idPetitorioQueja?: number,
  flApelacion?: string,
  idTipoRespuestaInstancia1?: number,
  flMismoTramite?: string,
  idActoTramiteCasoGuardado?: string,
  idTipoRespuestaQueja?: number,
  flConcedeApelacion?: string,
  flApelacionFiscal?: Boolean,
  flConsentidoInstancia1?: Boolean,
  idActoTramiteResultadoSujeto?: string,
}
