export enum TIPO_BIOMETRIA {
  HUELLA = 241,
  FOTO = 242,
  SENA = 243,
}

export enum IDOAID {
  FOTO = 10,
  SENA = 12,
  HUELLA = 13,
}

export enum HUELLA {
  PULGAR_DERECHO = 423,
  INDICE_DERECHO = 424,
  MEDIO_DERECHO = 425,
  ANULAR_DERECHO = 426,
  MENIQUE_DERECHO = 427,
  PULGAR_IZQUIERDO = 428,
  INDICE_IZQUIERDO = 429,
  MEDIO_IZQUIERDO = 430,
  ANULAR_IZQUIERDO = 431,
  MENIQUE_IZQUIERDO = 432,
}

export enum CONTACTO {
  CORREO = 1,
  TELEFONO = 2,
  CELULAR = 3,
  CASILLA = 4,
}
