export const NO_GRUPO_CATALOGO = {
    SUPUESTO_APLIC: 'ID_N_SUPUESTO_APLIC',
    TIPO_MEDIDA_COERCION: 'ID_N_TIPO_MEDIDA_COERCION',
    TIPO_ACTIV_AGENDA: 'ID_N_TIPO_ACTIV_AGENDA',
    SENTENCIA_CONCLUSION_ANTICIPADA: 'ID_N_SENTENCIA_CONCLUSION_ANTICIPADA',
    TIPO_SENTENCIA: 'ID_N_TIPO_SENTENCIA',
}  as const