export interface BandejaContiendaResponse {
    idBandejaElevacion: string,
    idCaso: string,
    coCaso: string,
    idFiscalAsignado: string,
    noFiscalAsignado: string,
    noCargo: string,
    idJerarquia: number,
    coEntidad: string,
    idTipoEntidad: number,
    idTipoContienda: number,
    idTipoOrigen: number,
    idEtapa: string,
    noEtapa: string,
    fechaElevacion: string,
    horaElevacion: string,
    noEntidad: string,
    idEntidad: number,
    idActoTramiteCaso: string,
    idTipoElevacion: number,
    flgTieneEfe: number,
    estadoRegistro: number,
}