export interface ContiendasCompetencias {
  idBandejaElevacion: string,
  idCaso: string,
  codCaso: string,
  descripContienda: string,
  tipoContienda: string,
  fiscalAsignado: string,
  fiscaliaProcedencia: string,
  despacho:string,
  entidad:string,
  jerarquia:string,
  fechaElevacion: string,
  nombreDespacho: string,
  semaforoNumero: string,
  semaforoColor: string,
  semaforoTiempo: string,
  semaforoFecha: string,
  idEntidad: string,
  respuesta: string,
  observacion:string,
  fechaIngreso:string,
  hora: string,
  plazo: string
}
