export interface RespuestaElevacion {
    idBandejaElevacion: string,
    idActoTramiteCaso: string,
    idCaso: string,
    codCaso: string,
    fiscal: string,
    esCaso: number,
    esCuaderno: number,
    esPestana?:number,
    idEtapa ?:string,
    idTipoElevacion: number,
    descTipoElevacion: string,
    descResultado: string,
    descEtapa: string,
    descTramite: string,
    fechaElevacion: string,
    fechaResultado: string,
    delitos: string,
}
