export interface ResuelveContienda {
  etapa?: string,
  idBandejaElevacion?: string,
  idFiscalAsignado?: string,
  idTipoEntidad?: number,
  codigoEntidad?: string,
  idTipoResultado?: number,
  fechaDisposicion?: string | null,
  idMotivoCompetencia?: number,
  descripcion?: string,
  observaciones?: string,
  idActoTramiteEstado?: string,
  idCaso?: string,
  archivo?: string,
  flagTieneEfe?: string,
  idActoTramiteCaso?: string,
  idEstadoRegistro?: number,
  idAccionEstadoProvincial?: number,
  idTipoCopia?: number,
  idDocumento?: string,
  nombreArchivo?: string,
  fiscal?: string,
  entidad?: string,
  distritoFiscal?: string,
  pesoArchivo?: number,
}
