
export const ACUERDO_ACTA = {
    PAGO_TOTAL:'1',
    PAGO_PARCIAL:'2',
    DEPOSITO_JUDICIAL: 1,
    DEPOSITO_CUENTA_AGRAVIADO: 3,
    PAGO_DIRECTO_AGRAVIADO: 2,
    PERIODICIDAD_MENSUAL:1172,
    PERIODICIDAD_QUINCENAL:1170,
    PERIODICIDAD_PERSONALIZADO:1171,
    MONEDA_NUEVO_SOL:215,
    OBSERVACION_LENGTH:1000,
    OBSERVACION_OTROS_ACUERDOS_LENGTH:1000
}  as const
