export const REGISTRAR_PENAS = {
    // TIPO DE PRETENSIÓN
    TOTAL_POR_PRETENSION: 1368,
    PARCIAL_POR_PRETENSION: 1369,
    // IDENTIFICADOR DE PENA
    ID_N_PENA: "ID_N_PENA",
    // CONSTANTES PARA VALORES DE CLASE PENA
    LIMITATIVAS_DERECHO_CLASE_PENA: 1230,
    MULTA_CLASE_PENA: 1231,
    PRIVATIVA_LIBERTAD_CLASE_PENA: 1232,
    RESTRICTIVA_LIBERTAD_CLASE_PENA: 1233,
    // CONSTANTES PARA VALORES DE TIPO PENA
    INHABILITACION_ACCESORIA_TIPO_PENA: 1,
    INHABILITACION_PRINCIPAL_TIPO_PENA: 3,
    LIMITACION_DIAS_LIBRES_TIPO_PENA: 4,
    PRESTACION_SERVICIO_COMUNIDAD_TIPO_PENA: 5,
    EFECTIVA_TIPO_PENA: 6,
    RESERVA_FALLO_CONDENATORIO_TIPO_PENA: 7,
    SUSPENDIDA_TIPO_PENA: 8,
    VIDEOVIGILANCIA_TIPO_PENA: 9,
    // AÑOS DE REVISIÓN PARA CADENA PERPETUA
    ANHOS_REVISION_CADENA_PERPETUA: 35,
    LIMITE_MONTO_MULTA:99999999.99
  } as const;
  