import {
  iFolderSearch,
  iTooltip,
  iChevronRight,
  iFilterShow,
  iFolderExclamation,
  iTable,
  iFileDownload,
  iPosit,
  iArrowRight,
  iFileAdd,
  iFiles,
  iFileSearch,
  iUsers,
  iFileInput,
  iClose,
  iDownload,
  iSearch,
  iFolderSolid,
  iAttach,
  iReAsign,
  iCheckCircle,
  iTrash,
  iEdit,
  iAdd,
  iCheck,
  iChevronLeft,
  iSend,
  iTrashCan,
  iSign,
  iDeny,
  iArrowLeft,
  iSave,
  iViewFile,
  iAddUser,
  iAlert,
  iFile,
  iAlertHexagonal,
  iCalendarClean,
  iClockDots,
  iFileRegister,
  iInfoCircle,
  iPlayCircle,
  iReset,
  iRestaurar,
  iEnviar,
  iFirmaMasiva,
  iSmartPhone,
  iTracing,
  iTrashMpe,
  iPhone,
  iMail,
  iPin,
  iDownloadFile,
  iFileUpload,
  iFolderMagnifyingGlass,
  iEye,
  iChevronUp,
  iChevronDown,
  iChevronOrder,
  iFileFull,
  iAlerta,
  iAltavoz,
  iEliminarBloqueado,
  iPrint,
  iTimer,
  iBell,
  iSearchMpe,
  iUsdCircle,
  iFileLock,
  iFileAudio,
  iFileVideo,
  iFileImage,
  iPdf
} from 'ngx-mpfn-dev-icojs-regular';

const ICONOS = [
  { nombre: 'iFolderSearch', icono: iFolderSearch },
  { nombre: 'iTooltip', icono: iTooltip },
  { nombre: 'iChevronRight', icono: iChevronRight },
  { nombre: 'iFilterShow', icono: iFilterShow },
  { nombre: 'iFolderExclamation', icono: iFolderExclamation },
  { nombre: 'iTable', icono: iTable },
  { nombre: 'iFileDownload', icono: iFileDownload },
  { nombre: 'iPosit', icono: iPosit },
  { nombre: 'iArrowRight', icono: iArrowRight },
  { nombre: 'iFileAdd', icono: iFileAdd },
  { nombre: 'iFiles', icono: iFiles },
  { nombre: 'iFileSearch', icono: iFileSearch },
  { nombre: 'iUsers', icono: iUsers },
  { nombre: 'iFileInput', icono: iFileInput },
  { nombre: 'iClose', icono: iClose },
  { nombre: 'iDownload', icono: iDownload },
  { nombre: 'iSearch', icono: iSearch },
  { nombre: 'iFolderSolid', icono: iFolderSolid },
  { nombre: 'iAttach', icono: iAttach },
  { nombre: 'iReAsign', icono: iReAsign },
  { nombre: 'iCheckCircle', icono: iCheckCircle },
  { nombre: 'iTrash', icono: iTrash },
  { nombre: 'iEdit', icono: iEdit },
  { nombre: 'iAdd', icono: iAdd },
  { nombre: 'iCheck', icono: iCheck },
  { nombre: 'iChevronLeft', icono: iChevronLeft },
  { nombre: 'iSend', icono: iSend },
  { nombre: 'iTrashCan', icono: iTrashCan },
  { nombre: 'iSign', icono: iSign },
  { nombre: 'iDeny', icono: iDeny },
  { nombre: 'iArrowLeft', icono: iArrowLeft },
  { nombre: 'iSave', icono: iSave },
  { nombre: 'iViewFile', icono: iViewFile },
  { nombre: 'iAddUser', icono: iAddUser },
  { nombre: 'iAlert', icono: iAlert },
  { nombre: 'iFile', icono: iFile },
  { nombre: 'iAlertHexagonal', icono: iAlertHexagonal },
  { nombre: 'iCalendarClean', icono: iCalendarClean },
  { nombre: 'iClockDots', icono: iClockDots },
  { nombre: 'iFileRegister', icono: iFileRegister },
  { nombre: 'iInfoCircle', icono: iInfoCircle },
  { nombre: 'iPlayCircle', icono: iPlayCircle },
  { nombre: 'iReset', icono: iReset },
  { nombre: 'iRestaurar', icono: iRestaurar },
  { nombre: 'iEnviar', icono: iEnviar },
  { nombre: 'iFirmaMasiva', icono: iFirmaMasiva },
  { nombre: 'iSmartPhone', icono: iSmartPhone },
  { nombre: 'iTracing', icono: iTracing },
  { nombre: 'iTrashMpe', icono: iTrashMpe },
  { nombre: 'iPhone', icono: iPhone },
  { nombre: 'iMail', icono: iMail },
  { nombre: 'iPin', icono: iPin },
  { nombre: 'iArrowLeft', icono: iArrowLeft },
  { nombre: 'iDownloadFile', icono: iDownloadFile },
  { nombre: 'iFileUpload', icono: iFileUpload },
  { nombre: 'iFolderMagnifyingGlass', icono: iFolderMagnifyingGlass },
  { nombre: 'iChevronUp', icono: iChevronUp },
  { nombre: 'iChevronDown', icono: iChevronDown },
  { nombre: 'iChevronOrder', icono: iChevronOrder },
  { nombre: 'iEye', icono: iEye },
  { nombre: 'iFileFull', icono: iFileFull },
  { nombre: 'iAlerta', icono: iAlerta },
  { nombre: 'iAltavoz', icono: iAltavoz },
  { nombre: 'iEliminarBloqueado', icono: iEliminarBloqueado },
  { nombre: 'iPrint', icono: iPrint },
  { nombre: 'iBell', icono: iBell },
  { nombre: 'iTimer', icono: iTimer },
  { nombre: 'iSearchMpe', icono: iSearchMpe },
  { nombre: 'iUsdCircle', icono: iUsdCircle },
  { nombre: 'iFileLock', icono: iFileLock },
  { nombre: 'iFileAudio', icono: iFileAudio },
  { nombre: 'iFileVideo', icono: iFileVideo },
  { nombre: 'iFileImage', icono: iFileImage },
  { nombre: 'iPdf', icono: iPdf },
]

export const obtenerIcono = ( nombre: string ) => {
  return ICONOS.find( icono => icono.nombre === nombre )?.icono
};
