
export const DESARROLLO_JUICIO_ORAL = {
    CITACION_VIRTUAL: 1223,
    CITACION_PRESENCIAL: 1222,
    ALEGATOS_CLAUSURA: '018',
    ACUSACION_COMPLEMENTARIA: '008',
    DESVINCULACION_JURIDICA: '009'
} as const
