export enum ID_N_TIPO_RESULTADO {
    FUNDADO_PROCEDENTE = 1105,
    INFUNDADO_IMPROCENDENTE = 1106,
  }

  export enum ID_N_RESULTADO_TERMINACION_ANTICIPADA {
    SENTENCIA_TERMINACION_ANTICIPADA_TOTAL = 1107,
    SENTENCIA_TERMINACION_ANTICIPADA_PARCIAL = 1108,
    AUTO_DESAPRUEBA_TERMINACION_ANTICIPADA = 1109
  }