export interface CasoElevacionActuado {
    /*id: number,
    plazo: string,
    numeroCaso: string,
    origen: string,
    tipoRemitente: string,
    remitente: string,
    telefono: string,
    correo: string,
    fechaIngreso: string,
    horaIngreso: string,
    cantidadPartes: number,
    leido: boolean,
    semaforoNro: string,
    semaforoColor: string,
    semaforoTiempo: string,*/

    idBandejaElevacion: string,
    idCaso: string,
    codigoCaso: string,
    idTipoOrigen: string,
    tipoOrigen: string,
    tipoPerfil: string,
    nombreCompleto: string,
    etapa: string,
    fechaElevacion: string,
    nombreDespacho: string,
    semaforoNro: string,
    semaforoColor: string,
    semaforoTiempo: string,
    semaforoFecha: string,
    idEntidad: string,
    respuesta: string,
    observacion:string,
    fechaIngreso:string,
    hora: string, 
    plazo: string
}
